apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    project: roboshop
    environment: dev
    purpose: poc  
spec:
  containers:
  - name: container1
    image: nginx
  - name: container2
    image: almalinux     