apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
spec:
  containers: 
  - name: nginx
    image: nginx
    resources:
      requests: #soft limit
        cpu: "100m" #1000milli core is 1 cpu
        ram: "128Mi"
      limits:  #hard limit
        cpu: "150m"
        ram: "256Mi"