apiVersion: v1
kind: Pod
metadata:
  name: envfrom-demo
spec:
  containers:
    - name: app-container
      image: nginx
      envFrom:                 # Injects all keys at once
        - configMapRef:
            name: configmap-demo # Must match the exact name of your ConfigMap